---
title: "Notebook for combining all publication plots"
output: html_notebook
---

```{r}
#plyr can be used to manipulate data frames
library(plyr)
library(svglite)
#ggplot is good for plotting
library(ggplot2)
#lmerTest loads mixed effects regressions and according t/z-tests
library(lmerTest)
```

```{r}
dat<-read.csv('/Users/swu/Desktop/research/motif_learning/data/simonsays_ex2/data.csv')
print(c('n motif = ', length(unique(dat[dat$traincondition=='m1',]$ID)), ', n  indep = ', length(unique(dat[dat$traincondition=='ind',]$ID))))
dat$trialposition<-rep((1:12),length(unique(dat$ID))*64)
dat$positioncorrect<-ifelse(dat$recallcollect == dat$instructioncollect,1,0)
dat$repetition<-rep(FALSE, nrow(dat))
dat$immediaterepetition<-rep(FALSE, nrow(dat))

dat_a<-read.csv('/Users/swu/Desktop/research/motif_learning/data/simonsays_ex2/accdata.csv')

dat_a$repetition<-rep(FALSE, nrow(dat_a)) # initialize data column that detects exact sequence repetition
dat_a$immediaterepetition<-rep(FALSE, nrow(dat_a))


for(id in unique(dat$ID)) {
  thisparticipant<-dat[dat$ID == id & dat$blockcollect == 'train',] # training set
  for (trial in 2:40){ # exclude the first trial
    repetition<-FALSE
    previousrepetition<-FALSE # exactly repeating the previous trial
    for (prev in 1:(trial-1)){ # iterate through previous trials
    if(identical(thisparticipant[thisparticipant$trialnumber == trial,]$instructioncollect,thisparticipant[thisparticipant$trialnumber == prev,]$instructioncollect)){
      repetition<-TRUE
      if (prev == trial-1){previousrepetition<-TRUE}
      break
    }
    }
    if(repetition == TRUE){
      dat[dat$ID == id & dat$blockcollect == 'train' & dat$trialcollect == trial,]$repetition = TRUE
    }
    if(previousrepetition == TRUE){
      dat[dat$ID == id & dat$blockcollect == 'train' & dat$trialcollect == trial,]$immediaterepetition = TRUE
    }    
    }
  }


dat_a_train <-subset(dat_a, blockcollect=='train')

#full model

dat_a_train$condition<-as.factor(dat_a_train$condition)
dat_a_train$condition<-relevel(dat_a_train$condition,ref="ind")

#null model doesn't contain condition, but fixed and random intercept
mnull<-lmer(correctcollect~1+(1|ID), data=dat_a_train)
#alternative model contains condition is fixed effect
malternative<-lmer(correctcollect~condition+(1|ID), data=dat_a_train)
#is the alternative model significantly better than the null model
anova(mnull, malternative)
```

```{r}
summary(malternative)
```
```{r}
dat_a_train <-subset(dat_a, blockcollect=='train')
#standard error function
se<-function(x){sd(x)/sqrt(length(x))}
dat_a_train<-dat_a_train[dat_a_train['timecollect']<20000,]# filter out more than 20s responses
#summarize data by condition
# sort according to the column of trial instruction, with different trial instructions
dpsubjects<-ddply(dat_a_train,.(ID,condition), summarize, meanacc=mean(correctcollect), se=se(correctcollect))
#dpsubjects$condition<-ifelse(dpsubjects$condition=="ind", "Random", "Motif")

dpgroups<-ddply(dpsubjects,.(condition), summarize, m=mean(meanacc), se=se(meanacc))

#creat plot
p1 <- ggplot(dpgroups, aes(y=m, x=condition, fill=condition)) +
  #show mean
  stat_summary(fun = mean, geom = "bar", position = "dodge", color='black', width=0.5) + 
  #points
  geom_point()+
  #error bars +/- SEs
  geom_errorbar(aes(ymin=m-se, ymax=m+se),color='black', width = .25, position=position_dodge((width=0.9))) +
  scale_y_continuous(limits = c(0, 1), expand = c(0, 0))+

  #ylab
  ylab("Empricial Accuracy")+
  #x-lab
  xlab("Group")+ 
  #theme
  theme_classic()+
  #fills
  scale_fill_manual(values=(c("#7F557D", "#80AA82")))+
  #theme change
  theme( strip.background=element_blank(), legend.key=element_rect(color=NA), legend.position="none")+ scale_x_discrete(labels=c("Fixed", "Variable"))+
  
  #title
  ggtitle("Behavioral Results")
  ggsave(file = "./fig/exp2/trainacc.svg")                       # Export ggplot2 plot


#show
p1
```


```{r}
se<-function(x){sd(x)/sqrt(length(x))}

dat<-read.csv('/Users/swu/Desktop/research/motif_learning/data/simonsays_ex2/data.csv')
dat$trialposition<-rep((1:12),length(unique(dat$ID))*64)
dat$positioncorrect<-ifelse(dat$recallcollect == dat$instructioncollect,1,0)

dat_test<-dat[dat$blockcollect == 'test',]

# obtain the learned variables
dat_test$lv1<- rep(subset(subset(subset(dat, trialcollect == 1), blockcollect == 'train'),trialposition == 2)$instructioncollect, each = 24*12)
dat_test$lv2<- rep(subset(subset(subset(dat, trialcollect == 1), blockcollect == 'train'),trialposition == 6)$instructioncollect, each = 24*12) # learned variable 2
dat_test$lv3<- rep(subset(subset(subset(dat, trialcollect == 1), blockcollect == 'train'),trialposition == 10)$instructioncollect, each = 24*12)
  
dat_test$tv1 <- rep(subset(subset(dat, blockcollect == 'test'),trialposition == 2)$instructioncollect, each = 12) # tested variable 1 
dat_test$tv2 <- rep(subset(subset(dat, blockcollect == 'test'),trialposition == 6)$instructioncollect, each = 12) # tested variable 2
dat_test$tv3 <- rep(subset(subset(dat, blockcollect == 'test'),trialposition == 10)$instructioncollect, each = 12) # tested variable 3
# tested variable is the same as trained variable for the control group
dat_test$coincide<- ifelse((dat_test$traincondition=='ind') & (dat_test$lv1==dat_test$tv1) & (dat_test$lv2==dat_test$tv2) & (dat_test$lv3==dat_test$tv3),1,0) 

dat_a<-read.csv('/Users/swu/Desktop/research/motif_learning/data/simonsays_ex2/accdata.csv')

dat_a_test<-subset(dat_a, blockcollect == 'test' & trialcollect<=24)
dat_a_test[c('coincide', 'lv1', 'lv2', 'lv3', 'tv1', 'tv2', 'tv3')] <- subset(dat_test, (trialposition ==1),select = c(coincide,lv1,lv2,lv3,tv1,tv2,tv3))
dat_a_test<-dat_a_test[dat_a_test$coincide == 0 ,] # the variable instantiations in the test trials are not the same

#summarize data by traincondition
dpsubjects<-ddply(dat_a_test,.(ID,traincondition), summarize, meanacc=mean(correctcollect), se=se(correctcollect))

msubjects<-dpsubjects[dpsubjects$traincondition %in% c('m1','ind'),]
msubjects$transfertype<-ifelse(msubjects$traincondition %in% c('m1'),'m1',0)
msubjects$transfertype<-ifelse(msubjects$traincondition %in% c('ind'),'ind',msubjects$transfertype)

dpgroupind<-ddply(msubjects,.(transfertype), summarize, m=mean(meanacc), se=se(meanacc))


```

```{r}
p5 <- ggplot(dpgroupind, aes(y=m, x=transfertype, fill=transfertype)) +
  #show mean
  stat_summary(fun = mean, geom = "bar", position = "dodge", color='black', width=0.5) + 
  #points
  geom_point()+
  #error bars +/- SEs
  geom_errorbar(aes(ymin=m-se, ymax=m+se),color='black', width = .25, position=position_dodge((width=0.9))) +
  #ylab
  ylab("Empirical Accuracy")+
  #x-lab
  xlab("Group")+ 
  scale_y_continuous(limits = c(0, 1), expand = c(0, 0))+

  #theme
  theme_classic()+
  #fills
  scale_fill_manual(values=(c("#7F557D", "#80AA82")))+
  #theme change
  theme(strip.background=element_blank(), legend.key=element_rect(color=NA), legend.position="none")+ scale_x_discrete(labels=c("Fixed", "Variable"))+
  
  #title
  ggtitle("Behavioral Results")
  ggsave(file = "./fig/exp2/testacc.svg")                       # Export ggplot2 plot



p5

```


```{r}
dat_m<-read.csv('/Users/swu/Desktop/research/motif_learning/data/simonsays_ex2/simulation_data_model_transition_recall_2.csv')
dpsubjects<-ddply(dat_m,.(ID,blockcollect,condition), summarize, meanacc=mean(correctcollect))
dat_m$traincondition = rep(subset(dpsubjects, blockcollect == 'train')$condition, each=64)

dat_m_train <-subset(dat_m, blockcollect=='train')


#full model

dat_m_train$condition<-as.factor(dat_m_train$condition)


dat_m_train$condition<-relevel(dat_m_train$condition,ref="ind")

#null model doesn't contain condition, but fixed and random intercept
mnull<-lmer(correctcollect~1+(1|ID), data=dat_m_train)
#alternative model contains condition is fixed effect
malternative<-lmer(correctcollect~condition+(1|ID), data=dat_m_train)
#is the alternative model significantly better than the null model
anova(mnull, malternative)


```



```{r}
dat_m_train$condition<-relevel(dat_m_train$condition,ref="ind")
dat_m_train <-subset(dat_m, blockcollect=='train')
#standard error function
se<-function(x){sd(x)/sqrt(length(x))}
#summarize data by condition
# sort according to the column of trial instruction, with different trial instructions
dpsubjects<-ddply(dat_m_train,.(ID,condition), summarize, meanacc=mean(correctcollect), se=se(correctcollect))
#dpsubjects$condition<-ifelse(dpsubjects$condition=="ind", "Random", "Motif")

dpgroups<-ddply(dpsubjects,.(condition), summarize, m=mean(meanacc), se=se(meanacc))

#creat plot
p2 <- ggplot(dpgroups, aes(y=m, x=condition, fill=condition)) +
  #show mean
  stat_summary(fun = mean, geom = "bar", position = "dodge", color='black', width=0.5) + 
  #points
  geom_point()+
  #error bars +/- SEs
  geom_errorbar(aes(ymin=m-se, ymax=m+se),color='black', width = .25, position=position_dodge((width=0.9))) +
  scale_y_continuous(limits = c(0, 1), expand = c(0, 0))+

  #ylab
  ylab("Generative Accuracy")+
  #x-lab
  xlab("Group")+ 
  #theme
  theme_classic()+
  #fills
  scale_fill_manual(values=(c("#7F557D", "#80AA82")))+
  #theme change
  theme(strip.background=element_blank(), legend.key=element_rect(color=NA), legend.position="none")+ scale_x_discrete(labels=c("Fixed", "Variable"))+
  
  #title
  ggtitle("Model Prediction")
  ggsave(file = "./fig/exp2/simulationtrainacc.svg")                       # Export ggplot2 plot


#show
p2
```
```{r}
se<-function(x){sd(x)/sqrt(length(x))}
dat_m_test<-subset(dat_m, blockcollect == 'test')
dat_m_test$traincondition<-as.factor(dat_m_test$traincondition)
dat_m_test$traincondition<-relevel(dat_m_test$traincondition,ref="ind")

#null model doesn't contain condition, but fixed and random intercept
mnull<-lmer(correctcollect~1+(1|ID), data=dat_m_test)
#alternative model contains condition is fixed effect
malternative<-lmer(correctcollect~traincondition+(1|ID), data=dat_m_test)
#is the alternative model significantly better than the null model
anova(mnull, malternative)
summary(malternative)
```


```{r}
se<-function(x){sd(x)/sqrt(length(x))}
dat_m_test<-subset(dat_m, blockcollect == 'test')

#summarize data by traincondition
dpsubjects<-ddply(dat_m_test,.(ID,traincondition), summarize, meanacc=mean(correctcollect), se=se(correctcollect))

msubjects<-dpsubjects[dpsubjects$traincondition %in% c('m1','ind'),]
msubjects$transfertype<-ifelse(msubjects$traincondition %in% c('m1'),'m1',0)
msubjects$transfertype<-ifelse(msubjects$traincondition %in% c('ind'),'ind',msubjects$transfertype)

dpgroupind<-ddply(msubjects,.(transfertype), summarize, m=mean(meanacc), se=se(meanacc))

p6 <- ggplot(dpgroupind, aes(y=m, x=transfertype, fill=transfertype)) +
  #show mean
  stat_summary(fun = mean, geom = "bar", position = "dodge", color='black', width=0.5) + 
  #points
  geom_point()+
  #error bars +/- SEs
  geom_errorbar(aes(ymin=m-se, ymax=m+se),color='black', width = .25, position=position_dodge((width=0.9))) +
  #ylab
  ylab("Generative Accuracy")+
  #x-lab
  xlab("Group")+ 
  scale_y_continuous(limits = c(0, 1), expand = c(0, 0))+

  #theme
  theme_classic()+
  #fills
  scale_fill_manual(values=(c("#7F557D", "#80AA82")))+
  #theme change
  theme(strip.background=element_blank(), legend.key=element_rect(color=NA), legend.position="none")+ scale_x_discrete(labels=c("Fixed", "Variable"))+
  
  #title
  ggtitle("Model Prediction")
  ggsave(file = "./fig/exp2/simulationtestacc.svg")                       # Export ggplot2 plot



p6
```
```{r}
dat<-read.csv('/Users/swu/Desktop/research/motif_learning/data/simonsays_ex2/data.csv')
dat$logRT <-log(dat$timecollect)
dat$trialposition<-rep((1:12),length(unique(dat$ID))*64) # keypress position
dat$positioncorrect<-ifelse(dat$recallcollect == dat$instructioncollect,1,0)
dat$postmistake<-c(0,dat$positioncorrect[0:(length(dat$positioncorrect)-1)])# mark post mistake positions
dat$chunkbeginning<-rep(c(1,0,0,0,1,0,0,0,1,0,0,0),length(unique(dat$ID))*64) # keypress position
dat$chunkbeginningorend<-rep(c(1,0,0,1,1,0,0,1,1,0,0,1),length(unique(dat$ID))*64) # keypress position
dat$chunkend<-rep(c(0,0,0,1,0,0,0,1,0,0,0,1),length(unique(dat$ID))*64) # keypress position
dat_a<-read.csv('/Users/swu/Desktop/research/motif_learning/data/simonsays_ex2/accdata.csv')
dat_a_train <-subset(dat_a, blockcollect=='train')
dat_a$logRT <-log(dat_a$timecollect)
dat$repetition<-rep(FALSE, nrow(dat))
dat$immediaterepetition<-rep(FALSE, nrow(dat))
dat_a$repetition<-rep(FALSE, nrow(dat_a))
dat_a$immediaterepetition<-rep(FALSE, nrow(dat_a))
dat$nrep<-rep(0, nrow(dat))
dat_a$nrep<-rep(0, nrow(dat_a))


for(id in unique(dat$ID)) {
  thisparticipant<-dat[dat$ID == id & dat$blockcollect == 'train',] # training set
  for (trial in 2:40){ # exclude the first trial
    repetition<-FALSE
    previousrepetition<-FALSE # exactly repeating the previous trial
    for (prev in (trial-1):1){ # iterate through previous trials
    if(identical(thisparticipant[thisparticipant$trialcollect == trial,]$instructioncollect,thisparticipant[thisparticipant$trialcollect == prev,]$instructioncollect)){
      repetition<-TRUE
      nr<-dat_a[dat_a$ID == id & dat_a$blockcollect == 'train' & dat_a$trialcollect == prev,]$nrep + 1
      if (prev == trial-1){previousrepetition<-TRUE}
      break
    }
    }
    if(repetition == TRUE){
      dat[dat$ID == id & dat$blockcollect == 'train' & dat$trialcollect == trial,]$nrep = nr
      dat_a[dat_a$ID == id & dat_a$blockcollect == 'train' & dat_a$trialcollect == trial,]$nrep = nr
      dat[dat$ID == id & dat$blockcollect == 'train' & dat$trialcollect == trial,]$repetition = TRUE
      dat_a[dat_a$ID == id & dat_a$blockcollect == 'train' & dat_a$trialcollect == trial,]$repetition = TRUE
    }
    if(previousrepetition == TRUE){
      dat[dat$ID == id & dat$blockcollect == 'train' & dat$trialcollect == trial,]$immediaterepetition = TRUE
      dat_a[dat_a$ID == id & dat_a$blockcollect == 'train' & dat_a$trialcollect == trial,]$immediaterepetition = TRUE
    }
    
    }
  }



for(id in unique(dat$ID)) {
  thisparticipant<-dat[dat$ID == id & dat$blockcollect == 'test',] # training set
  for (trial in 2:24){ # exclude the first trial
    repetition<-FALSE
    previousrepetition<-FALSE # exactly repeating the previous trial
    for (prev in (trial-1):1){ # iterate through previous trials
    if(identical(thisparticipant[thisparticipant$trialcollect == trial,]$instructioncollect,thisparticipant[thisparticipant$trialcollect == prev,]$instructioncollect)){
      repetition<-TRUE
      nr<-dat_a[dat_a$ID == id & dat_a$blockcollect == 'test' & dat_a$trialcollect == prev,]$nrep + 1
      if (prev == trial-1){previousrepetition<-TRUE}
      break
    }
    }
    if(repetition == TRUE){
      dat[dat$ID == id & dat$blockcollect == 'test' & dat$trialcollect == trial,]$nrep = nr
      dat_a[dat_a$ID == id & dat_a$blockcollect == 'test' & dat_a$trialcollect == trial,]$nrep = nr
      dat[dat$ID == id & dat$blockcollect == 'test' & dat$trialcollect == trial,]$repetition = TRUE
      dat_a[dat_a$ID == id & dat_a$blockcollect == 'test' & dat_a$trialcollect == trial,]$repetition = TRUE
    }
    if(previousrepetition == TRUE){
      dat[dat$ID == id & dat$blockcollect == 'test' & dat$trialcollect == trial,]$immediaterepetition = TRUE
      dat_a[dat_a$ID == id & dat_a$blockcollect == 'test' & dat_a$trialcollect == trial,]$immediaterepetition = TRUE
    }
    
    }
  }

#full model
dat_a_train<-dat_a[dat_a$blockcollect=='train',]
dat_a_train$condition<-as.factor(dat_a_train$condition)
dat_a_train$condition<-relevel(dat_a_train$condition,ref="ind")


dat_test<-dat[dat$blockcollect == 'test',]
se<-function(x){sd(x)/sqrt(length(x))}

```



```{r}
dat$trialposition<-rep((1:12),length(unique(dat$ID))*64)
dat$positioncorrect<-ifelse(dat$recallcollect == dat$instructioncollect,1,0)
dat$variableposition<-ifelse(dat$trialposition==2 | dat$trialposition==6 | dat$trialposition==10,TRUE,FALSE)

dat_train<-dat[dat$blockcollect == 'train',]

dat_train$traincondition<-as.factor(dat_train$traincondition)
dat_train$traincondition<-relevel(dat_train$traincondition,ref="ind")
dat_train$variableposition<-as.factor(dat_train$variableposition)

dat_train$trialposition<-scale(dat_train$trialposition)
dat_train$trialcollect<-scale(dat_train$trialcollect)[,1]
dat_train$nrep<-scale(dat_train$nrep, scale = FALSE)
dat_train$chunkbeginningorend<- ifelse((dat_train$chunkbeginningorend == 1), TRUE, FALSE)


#null model doesn't contain condition, but fixed and random intercept
mnull<-glmer(positioncorrect ~ 1 + (1|ID) , data=dat_train, family = binomial)
m1<-glmer(positioncorrect~ 1 + trialposition +(1|ID), data=dat_train, family = binomial)
m2<-glmer(positioncorrect~ 1 + trialposition + trialcollect +(1|ID), data=dat_train, family = binomial)
m3<-glmer(positioncorrect~ 1 + trialposition+ trialcollect + chunkbeginningorend+(1|ID) , data=dat_train, family = binomial)
m4<-glmer(positioncorrect~ 1 + trialposition+ trialcollect + chunkbeginningorend+nrep+(1|ID), data=dat_train, family = binomial)
#m5<-glmer(positioncorrect~ 1 + trialposition+ trialcollect + chunkbeginningorend+nrep+ variableposition + (1|ID), data=dat_train, family = binomial)
m6<-glmer(positioncorrect~ 1 + trialposition+ trialcollect + chunkbeginningorend + nrep + traincondition + (1|ID), data=dat_train, family = binomial)
m8<-glmer(positioncorrect~ 1 + trialposition+ trialcollect*traincondition + chunkbeginningorend + nrep + (1|ID), data=dat_train, family = binomial)

anova(mnull, m1)
summary(m1)
anova(m1, m2)
summary(m2)
anova(m2, m3)
summary(m3)
anova(m3,m4)
summary(m4)
anova(m4,m6)
summary(m6)
anova(m6,m8)
summary(m8)
```
```{r}
m80<-glmer(positioncorrect~ 1 + trialposition+ trialcollect*traincondition + chunkbeginningorend + nrep + (1|ID), data=dat_train, family = binomial)
# m81<-glmer(positioncorrect~ 1 + trialposition+ trialcollect*traincondition + chunkbeginningorend + nrep + (1 + trialcollect|ID), data=dat_train, family = binomial) # does not converge

m82<-glmer(positioncorrect~ 1 + trialposition+ trialcollect*traincondition + chunkbeginningorend + nrep + (1 + trialposition|ID), data=dat_train, family = binomial)

# m83<-glmer(positioncorrect~ 1 + trialposition+ trialcollect*traincondition + chunkbeginningorend + nrep + (1 + trialposition + trialcollect|ID), data=dat_train, family = binomial) # does not converge

anova(m80, m82)
summary(m82)
```


```{r}

library(sjPlot) #for plotting lmer and glmer mods
library(sjmisc) 
library(effects)
library(sjstats) #use for r2 functions



p3 <- sjPlot::plot_model(m82, terms = c('trainconditionm1', 'trialcollect:trainconditionm1','chunkbeginningorendTRUE'), transform = NULL,show.values=TRUE, show.p=FALSE, show.intercept = TRUE, show.zeroinf = TRUE, value.offset = 0.3, show.data= TRUE, vline.color = 'gray',color = 'blue', axis.labels = c('Variable x Trial','Chunk Boundary','Variable'), title="Regression Coefficients") + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +   theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black"),legend.position = "top") 
ggsave(file = "./fig/exp2/trainlmer.svg")                       # Export ggplot2 plot
#axis.labels=c("Group M1", "Group M2", "Trial collect", "Recall position", "Chunk bundary", "N repetition", "M1 x Trial collect", "M2 x Trial collect"),
sjPlot:: tab_model(m8, file = "")


p3 
```

```{r}

dat_test<-dat[dat$blockcollect == 'test',]

dat_test$lv1<- rep(subset(subset(subset(dat, trialcollect == 1), blockcollect == 'train'),trialposition == 2)$instructioncollect, each = 24*12)
dat_test$lv2<- rep(subset(subset(subset(dat, trialcollect == 1), blockcollect == 'train'),trialposition == 6)$instructioncollect, each = 24*12) # learned variable 2
dat_test$lv3<- rep(subset(subset(subset(dat, trialcollect == 1), blockcollect == 'train'),trialposition == 10)$instructioncollect, each = 24*12)
  
dat_test$tv1 <- rep(subset(subset(dat, blockcollect == 'test'),trialposition == 2)$instructioncollect, each = 12) # tested variable 1 
dat_test$tv2 <- rep(subset(subset(dat, blockcollect == 'test'),trialposition == 6)$instructioncollect, each = 12) # tested variable 2
dat_test$tv3 <- rep(subset(subset(dat, blockcollect == 'test'),trialposition == 10)$instructioncollect, each = 12) # tested variable 3
dat_test$coincide<- ifelse((dat_test$traincondition=='ind') & (dat_test$lv1==dat_test$tv1) & (dat_test$lv2==dat_test$tv2) & (dat_test$lv3==dat_test$tv3),1,0) # tested variable is the same as trained variable for the control group


dat_test<-dat[dat$blockcollect == 'test' & dat$trialcollect <=10,] # take the first xxx trials
dat_test$traincondition<-as.factor(dat_test$traincondition)
dat_test$traincondition<-relevel(dat_test$traincondition,ref="ind")
dat_test$variableposition<-as.factor(dat_test$variableposition)

dat_test$trialposition<-scale(dat_test$trialposition)
dat_test$trialcollect<-scale(dat_test$trialcollect)#[,1]
dat_test$nrep<-scale(dat_test$nrep, scale = FALSE)

dat_train$chunkbeginningorend<- ifelse((dat_train$chunkbeginningorend == 1), TRUE, FALSE)
dat_test$chunkbeginningorend<-as.factor(dat_test$chunkbeginningorend)

mnull<-glmer(positioncorrect ~ 1 + (1|ID) , data=dat_test, family = binomial)
m1<-glmer(positioncorrect~ 1 + trialposition +(1|ID), data=dat_test, family = binomial)
m2<-glmer(positioncorrect~ 1 + trialposition + trialcollect +(1|ID), data=dat_test, family = binomial)
m3<-glmer(positioncorrect~ 1 + trialposition+ trialcollect + chunkbeginningorend+(1|ID) , data=dat_test, family = binomial)
m4<-glmer(positioncorrect~ 1 + trialposition+ trialcollect + chunkbeginningorend+nrep+(1|ID), data=dat_test, family = binomial)
#m5<-glmer(positioncorrect~ 1 + trialposition+ trialcollect + chunkbeginningorend+nrep+ variableposition + (1|ID), data=dat_test, family = binomial)
m6<-glmer(positioncorrect~ 1 + trialposition+ trialcollect + chunkbeginningorend + nrep  + traincondition + (1|ID), data=dat_test, family = binomial)
#m7<-glmer(positioncorrect~ 1 + trialposition+ trialcollect + chunkbeginningorend + nrep + variableposition*traincondition + (1|ID), data=dat_test, family = binomial)
m8<-glmer(positioncorrect~ 1 + trialposition + chunkbeginningorend + nrep + trialcollect*traincondition + (1|ID), data=dat_test, family = binomial)

anova(mnull, m1)
summary(m1)
anova(m1, m2)
summary(m2)
anova(m2, m3)
summary(m3)
anova(m3,m4)
summary(m4)
anova(m4,m6)
summary(m6)

m6<-glmer(positioncorrect~ 1 + trialposition+ trialcollect + chunkbeginningorend + nrep  + traincondition + (1|ID), data=dat_test, family = binomial)
```

```{r}
m60<-glmer(positioncorrect~ 1 + trialposition+ trialcollect + chunkbeginningorend + nrep  + traincondition + (1|ID), data=dat_test, family = binomial)

#m61<-glmer(positioncorrect~ 1 + trialposition+ trialcollect + chunkbeginningorend + nrep  + traincondition + (1 + |ID), data=dat_test, family = binomial) # did not work

m62<-glmer(positioncorrect~ 1 + trialposition+ trialcollect + chunkbeginningorend + nrep  + traincondition + (1|ID), data=dat_test, family = binomial) #

m63<-glmer(positioncorrect~ 1 + trialposition+ trialcollect + chunkbeginningorend + nrep  + traincondition + (1|ID), data=dat_test, family = binomial)

summary(m60)
anova(m60, m63)

```


```{r}

library(sjPlot) #for plotting lmer and glmer mods
library(sjmisc) 
library(effects)
library(sjstats) #use for r2 functions
library(svglite)

p7 <- sjPlot::plot_model(m60, terms = c('trainconditionm1', 'chunkbeginningorend1'), transform = NULL,show.values=TRUE, show.p=FALSE, show.intercept = TRUE, show.zeroinf = TRUE, value.offset = 0.3, show.data= TRUE, vline.color = 'gray',color = 'blue', axis.labels = c('Variable', 'Chunk Boundary'), title="Regression Coefficients") + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))  +   theme(panel.grid.major = element_blank(),  panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black"),legend.position = "top") 
ggsave(file = "./fig/exp2/testlmer.svg")                       # Export ggplot2 plot

#axis.labels=c("Group M1", "Group M2", "Trial collect", "Recall position", "Chunk bundary", "N repetition", "M1 x Trial collect", "M2 x Trial collect"),
sjPlot:: tab_model(m6)

p7
```

```{r}
dat_subj<-read.csv('/Users/swu/Desktop/research/motif_learning/data/simonsays_ex2/accdata.csv')
dat_subj$trial<-rep((1:64),length(unique(dat_subj$ID)))
empirical_acc<-ddply(dat_subj, .(trial,condition), summarize, m=mean(correctcollect))

empirical_acc <- empirical_acc[empirical_acc$trial<=40,]
empirical_acc$trial<-scale(empirical_acc$trial)
linearmodel <- lm(m~trial, data=empirical_acc)
RSlinearmodel<- summary(linearmodel)$r.square
empirical_acc <- empirical_acc$m

dat_normal<-read.csv('/Users/swu/Desktop/research/motif_learning/data/simonsays_ex2/simulation_data_model_transition_recall.csv')
dat_normal$trial<-rep((1:64),length(unique(dat_normal$ID)))
dat_normal<-ddply(dat_normal, .(trial,condition), summarize, m=mean(correctcollect))

motif_learning <- dat_normal[dat_normal$trial<=40,]$m
conditions <-dat_normal[dat_normal$trial<=40,]$condition

dat_associative_learning<-read.csv('/Users/swu/Desktop/research/motif_learning/data/simonsays_ex2/simulation_data_model_transition_recall_associative_learning.csv')
dat_associative_learning$trial<-rep((1:64),length(unique(dat_associative_learning$ID)))
dat_associative_learning<-ddply(dat_associative_learning, .(trial,condition), summarize, m=mean(correctcollect))

associative_learning<-dat_associative_learning[dat_associative_learning$trial<=40,]$m

dat_projectional_lesioned<-read.csv('/Users/swu/Desktop/research/motif_learning/data/simonsays_ex2/simulation_data_model_transition_recall_leison_variable_motif.csv')
dat_projectional_lesioned$trial<-rep((1:64),length(unique(dat_projectional_lesioned$ID)))
dat_projectional_lesioned<-ddply(dat_projectional_lesioned, .(trial,condition), summarize, m=mean(correctcollect))

sequence_learning<-dat_projectional_lesioned[dat_projectional_lesioned$trial<=40,]$m

dfmc<-data.frame(empirical_acc,motif_learning,associative_learning,sequence_learning,conditions)

model <- lm(empirical_acc~motif_learning, data=dfmc)
RSmotiflearning<- summary(model)$r.squared

model <- lm(empirical_acc~associative_learning, data=dfmc)
RSassociative_learning<- summary(model)$r.squared

model <- lm(empirical_acc~sequence_learning, data=dfmc)
RSsequence_learning<- summary(model)$r.squared

# Create data
modelcomparison <- data.frame(
  name=c("Motif","Associative","Chunking") ,  
  value=c(RSmotiflearning,RSassociative_learning,RSsequence_learning))


#creat plot
p4 <- ggplot(modelcomparison, aes(y=value, x=reorder(name,+value))) +
  #show mean
  stat_summary(fun = mean, geom = "bar", position = "dodge", color='black', width=0.5) + 
  #points
  geom_point()+
  #error bars +/- SEs
  scale_y_continuous(expand = c(0, 0))+
  #ylab
  ylab("R-Squared")+
  #x-lab
  xlab("Model")+ 
  #theme
  theme_classic()+
  #theme change
  theme( strip.background=element_blank(), legend.key=element_rect(color=NA), legend.position="none")+
  
  #title
  ggtitle("Model Comparison")
  ggsave(file = "./fig/exp2/modelcomparison.svg")                       # Export ggplot2 plot

p4
```


```{r}
dat_subj<-read.csv('/Users/swu/Desktop/research/motif_learning/data/simonsays_ex2/accdata.csv')
dat_subj$trial<-rep((1:64),length(unique(dat_subj$ID)))
traincondition<-dat_subj$traincondition

empirical_acc<-ddply(dat_subj, .(trial,traincondition), summarize, m=mean(correctcollect))
empirical_acc <- empirical_acc[empirical_acc$trial>40,]
empirical_acc$trial<-scale(empirical_acc$trial)
linearmodel <- lm(m~trial, data=empirical_acc)
RSlinearmodel<- summary(linearmodel)$r.square
empirical_acc <- empirical_acc$m

dat_normal<-read.csv('/Users/swu/Desktop/research/motif_learning/data/simonsays_ex2/simulation_data_model_transition_recall.csv')
dat_normal$trial<-rep((1:64),length(unique(dat_normal$ID)))

dat_normal$traincondition<-traincondition
  
dat_normal<-ddply(dat_normal, .(trial,traincondition), summarize, m=mean(correctcollect))
conditions <-dat_normal[dat_normal$trial>40,]$traincondition
motif_learning <- dat_normal[dat_normal$trial>40,]$m

dat_associative_learning<-read.csv('/Users/swu/Desktop/research/motif_learning/data/simonsays_ex2/simulation_data_model_transition_recall_associative_learning.csv')
dat_associative_learning$traincondition<-traincondition

dat_associative_learning$trial<-rep((1:64),length(unique(dat_associative_learning$ID)))
dat_associative_learning<-ddply(dat_associative_learning, .(trial,traincondition), summarize, m=mean(correctcollect))

associative_learning<-dat_associative_learning[dat_associative_learning$trial>40,]$m

dat_projectional_lesioned<-read.csv('/Users/swu/Desktop/research/motif_learning/data/simonsays_ex2/simulation_data_model_transition_recall_leison_variable_motif.csv')
dat_projectional_lesioned$trial<-rep((1:64),length(unique(dat_projectional_lesioned$ID)))
dat_projectional_lesioned<-ddply(dat_projectional_lesioned, .(trial,traincondition), summarize, m=mean(correctcollect))

sequence_learning<-dat_projectional_lesioned[dat_projectional_lesioned$trial>40,]$m

dfmc<-data.frame(empirical_acc,motif_learning,associative_learning,sequence_learning,conditions)

model <- lm(empirical_acc~motif_learning, data=dfmc)
RSmotiflearning<- summary(model)$r.squared

model <- lm(empirical_acc~associative_learning, data=dfmc)
RSassociative_learning<- summary(model)$r.squared

model <- lm(empirical_acc~sequence_learning, data=dfmc)
RSsequence_learning<- summary(model)$r.squared

# Create data
modelcomparison <- data.frame(
  name=c("Motif","Associative","Chunking") ,  
  value=c(RSmotiflearning,RSassociative_learning,RSsequence_learning))


#creat plot
p8 <- ggplot(modelcomparison, aes(y=value, x=reorder(name,+value))) +
  #show mean
  stat_summary(fun = mean, geom = "bar", position = "dodge", color='black', width=0.5) + 
  #points
  geom_point()+
  #error bars +/- SEs
  scale_y_continuous(expand = c(0, 0))+
  #ylab
  ylab("R-Squared")+
  #x-lab
  xlab("Model")+ 
  #theme
  theme_classic()+
  #theme change
  theme( strip.background=element_blank(), legend.key=element_rect(color=NA), legend.position="none")+
  
  #title
  ggtitle("Model Comparison")
  ggsave(file = "./fig/exp2/modelcomparisontest.svg")                       # Export ggplot2 plot

p8
```
```{r,fig.width = 15,dpi = 200}
library(patchwork)
patchwork<-(p1 | p2 | p3 | p4)/(p5 | p6 | p7 | p8) + plot_layout(nrow = 2) +  plot_annotation(tag_levels = 'a') + plot_layout(widths = c(3,3,6,10), heights = c(3,3))
patchwork & theme(text = element_text(size=16))

ggsave(file = "./fig/exp2/combined.svg")                       # Export ggplot2 plot

```



```{r}
library(patchwork)
library(grid)
library(gridExtra)

pl_multi <- grid.draw(marrangeGrob(list(p1, p1, p1, p1, p1, p1), nrow = 2, ncol = 3))

#(p1 + p2 + p3 )/(p5 + p6 + p7)

#x11()
pl_multi

```

